### ISSUE TITLE
TypeError: 'type' object is not iterable

### ISSUE THREAD

**Issue by ghost** [swimlane/python-office365#5]
I want to count number of persons detected in a video stream at each frame. Then detected persons in each frame should addup into a total count of persons in the video. 

# This is the code I am using: 
import cv2
import sys

faceCascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

video_capture = cv2.VideoCapture(0)

while True:
     #Capture frame-by-frame

	ret, frame = video_capture.read()
	gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
	
	faces = faceCascade.detectMultiScale(
    	gray,
    	scaleFactor=1.1,
    	minNeighbors=5,
    	minSize=(30, 30),
	)
 
 #Draw a rectangle around the faces
	for (x, y, w, h) in faces:
    		cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
		print "FOUND", len(faces), "face"
		length = sum(len(faces) for s in str)
		

 #Display the resulting frame
	cv2.imshow('Video', frame)

	if cv2.waitKey(1) & 0xFF == ord('q'):
    		break

video_capture.release()

cv2.destroyAllWindows()

# Result:

afshan@afshan-VirtualBox:~/face_detection$ python facecount.py
FOUND 1 face
Traceback (most recent call last):
  File "facecount.py", line 25, in <module>
    length = sum(len(faces) for s in str)
TypeError: 'type' object is not iterable

**Comment by ghost** [comment]
# Solved

Tried an alternative method. Save terminal output to a text file and sum the count of detection using this code:

total = 0

with open('out.txt', 'r') as inp, open('output.txt', 'w') as outp:
   for line in inp:
       try:
           num = float(line)
           total += num
           outp.write(line)
       except ValueError:
           print('{} is not a number!'.format(line))

print('Total of all numbers: {}'.format(total))

**Comment by spencer-hanson** [comment]
I don't think you created the issue for the correct repository.. This is an Office 365 API python package, but I'm glad you solved your problem.
